[package]
name = "kompact_benchmarks"
version = "0.1.0"
edition = "2018"

[dependencies]
#kompact 				= { git = "https://github.com/kompics/kompact"}
kompact 				= { git = "https://github.com/kompics/kompact", rev = "94956af" }
omnipaxos               = { git = "https://github.com/anonsub0/omnipaxos", features = ["batch_accept"] }
benchmark_suite_shared 	= { path = "../shared_rust/" }
protobuf        		= "2"
futures         		= "0.1"
futures-cpupool 		= "0.1"
grpc 					= "0.6"
synchronoise 			= "1.0"
slog 					= {version = "2.4", features = ["max_level_debug", "release_max_level_info"]}
time 					= "0.1"
#tokio-core 				= "0.1"
num_cpus 				= "1"
parse_duration 			= "2"
rand 					= {version = "0.7", features = ["small_rng"]}
chrono                  = "0.4"
raft                    = "0.6.0-alpha"
uuid                    = { version = "0.8", features = ["v4"] }
memmap                  = "0.7.0"
hashbrown               = "0.8.0"
indexmap                = "1.4.0"
hdrhistogram            = "6.0"
hocon 					= {version = "0.3.6", default-features = false}
quanta                  = "0.7.2"
pretty-bytes            = {version = "0.2.2", optional = true}

[dev-dependencies]
uuid = { version = "0.8", features = ["v4"] }

[profile.release]
lto = true

[features]
travis_ci = ["slog/max_level_info", "slog/release_max_level_info"]

track_timeouts = [] # client keep tracks of which proposals timed out
track_latency = [] # measure latency for proposals
track_timestamps = []
measure_io = ["pretty-bytes"]
preloaded_log = []
use_pid_map = [] # assign nodes to specific process ids
periodic_client_logging = []
periodic_replica_logging = []
simulate_partition = [] # simulate livelock and deadlock scenarios

default = ["simulate_partition", "use_pid_map", "track_latency"]
